### ISSUE TITLE
Error in the without pageRange loop? 

### ISSUE THREAD

**Issue by Schizhats** [tariky/mighty-pdf-parser#1]
Hello, 

First of all thank you for your library, it helped me a lot! 

While using it I notice that the last page of my PDF is not read by your system if I don't give it any options. 

This is due to an error (unless I'm wrong) here:
https://github.com/tariky/mighty-pdf-parser/blob/a4f3a806506265e2f06ca31108c7ebe25f8c9bf2/lib/parser.js#L97

The line should be:
```JS
for (let index = 1; index <= pageCount; index++) {...}
```

For those who need a temporary solution (but not optimized) here is what I did:
```JS
const dataBuffer = fs.readFileSync(pathToPdf);
  const { pageCount } = await mightyPdfParser(dataBuffer);

  const options = {
    pageRange: true,
    startPage: 1,
    endPage: pageCount,
  };

  return await mightyPdfParser(dataBuffer, options);
```

As it is the fact of not having the option which makes that one passes in the bad loop, I recover a first time the number of pages detected by the algorithm to then give it to the options and thus pass in the good condition.

**Comment by tariky** [comment]
Hello, I was bit late with this answer. You are right, problem was on that line. Now it is fixed and updated.
